language: node_js
node_js: '12'

script:
  - echo Nothing to build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
